config:
    AZURE_SUBSCRIPTION_ID: "" # Please modify to your subscription
    AZURE_RESOURCE_GROUP: "" # Please modify to your Azure resource group
    AZURE_WORKSPACE: "" # Please modify to your Azure workspace
    AZURE_DATA_NAME: "" # Please modify to your AzureML data name
    DATA_DIR: "./dataset"
    CLOUD_DIR: "./cloud"
    HF_MODEL_NAME_OR_PATH: "Phi-3-small-128k-instruct-paper"
    IS_DEBUG: true
    USE_LOWPRIORITY_VM: true


evaluation:
  rest_endpoint: ""
  deployment_name: ""
